[pytest]
testpaths = tests
pythonpath = .
addopts =
    -ra
    --cov=app
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-report=html:htmlcov
filterwarnings =
    ignore::DeprecationWarning
