import type { PlanDefinition } from "./types";

export const PLANS: PlanDefinition[] = [
  {
    id: "free",
    name: "Free",
    tagline: "Explora Prediktia con acceso limitado",
    priceLabel: "$0",
    priceNote: "Siempre gratis",
    badge: "Incluido",
    gradient: "from-emerald-400 via-cyan-400 to-teal-500",
    glow: "shadow-[0_0_40px_-8px_rgba(52,211,153,0.45)]",
    ring: "ring-emerald-400/35",
    icon: "◇",
    features: [
      { label: "Partidos del día", included: true },
      { label: "Hasta 3 value picks diarios", included: true },
      { label: "Smart ACCA", included: false },
      { label: "Historial limitado (10)", included: true },
      { label: "Métricas avanzadas", included: false },
    ],
    cta: "Plan actual",
    ctaVariant: "free",
  },
  {
    id: "premium",
    name: "Premium",
    tagline: "Value bets y Smart ACCA sin límites",
    priceLabel: "$4.990",
    priceNote: "CLP / mes · Webpay Plus",
    badge: "Recomendado",
    gradient: "from-cyan-400 via-sky-500 to-violet-500",
    glow: "shadow-[0_0_48px_-8px_rgba(56,189,248,0.5)]",
    ring: "ring-cyan-400/45",
    icon: "◆",
    features: [
      { label: "Value bets completos", included: true, highlight: true },
      { label: "Smart ACCA (todos los perfiles)", included: true, highlight: true },
      { label: "Historial completo", included: true },
      { label: "Métricas avanzadas básicas", included: true },
      { label: "Alertas prioritarias", included: false },
    ],
    cta: "Hazte Premium",
    ctaVariant: "premium",
  },
  {
    id: "vip",
    name: "VIP",
    tagline: "Máximo rendimiento y soporte dedicado",
    priceLabel: "A medida",
    priceNote: "Contacto directo",
    badge: "Exclusivo",
    gradient: "from-violet-500 via-fuchsia-500 to-rose-500",
    glow: "shadow-[0_0_52px_-8px_rgba(168,85,247,0.55)]",
    ring: "ring-violet-400/45",
    icon: "✦",
    features: [
      { label: "Todo Premium", included: true, highlight: true },
      { label: "Métricas avanzadas completas", included: true },
      { label: "Alertas prioritarias", included: true },
      { label: "Soporte y contacto directo", included: true },
      { label: "Funciones futuras exclusivas", included: true },
    ],
    cta: "Contactar / Mejorar a VIP",
    ctaVariant: "vip",
  },
];
